import { Knex } from "knex";

export async function seed(knex: Knex): Promise<void> {
  const txn = await knex.transaction();
  // Deletes ALL existing entries
  try {
    await txn("users").del();

    // Inserts seed entries
    await txn("users").insert([
      {
        username: "chaewon",
        email: "imperfect@gmail.com",
        profile_pic: "test_image_user_profile.jpg",
        blog_image: "test_image_blog.jpg",
        password: "1234567",
        caption: "i am super cute",
        living_location: "Korea",
        status: "activated",
      },
      {
        username: "iu",
        email: "iu@gmail.com",
        profile_pic: "test2_image_user_profile.jpg",
        blog_image: "test2_image_blog.jpg",
        password: "1234",
        caption: "i am super cute",
        living_location: "Korea",
        status: "activated",
      },
      {
        username: "karina",
        email: "karina@gmail.com",
        profile_pic: "d-cat1.jpg",
        blog_image: "d-cat1.jpg",
        password: "123456",
        caption: "i am super cute",
        living_location: "Korea",
        status: "activated",
      },
      {
        username: "Sana",
        email: "Sana@gmail.com",
        profile_pic: "d-cat2.jpg",
        blog_image: "d-cat2.jpg",
        password: "123456",
        caption: "i am super cute",
        living_location: "Korea",
        status: "activated",
      },
      {
        username: "Timmy",
        email: "Timmy@gmail.com",
        profile_pic: "d-cat3.jpg",
        blog_image: "d-cat3.jpg",
        password: "123456",
        caption: "i am super cute",
        living_location: "Korea",
        status: "activated",
      },
      {
        username: "Jimmy",
        email: "Jimmy@gmail.com",
        profile_pic: "d-cat4.jpg",
        blog_image: "d-cat4.jpg",
        password: "123456",
        caption: "i am super cute",
        living_location: "Korea",
        status: "activated",
      },
      {
        username: "Anna",
        email: "Anna@gmail.com",
        profile_pic: "d-cat5.jpg",
        blog_image: "d-cat5.jpg",
        password: "123456",
        caption: "i am super cute",
        living_location: "Korea",
        status: "activated",
      },
      {
        username: "Momo",
        email: "Momo@gmail.com",
        profile_pic: "d-cat6.jpg",
        blog_image: "d-cat6.jpg",
        password: "123456",
        caption: "i am super cute",
        living_location: "Korea",
        status: "activated",
      },
      {
        username: "Mina",
        email: "Mina@gmail.com",
        profile_pic: "d-cat7.jpg",
        blog_image: "d-cat7.jpg",
        password: "123456",
        caption: "i am super cute",
        living_location: "Korea",
        status: "activated",
      },
      {
        username: "Hani",
        email: "Hani@gmail.com",
        profile_pic: "d-cat8.jpg",
        blog_image: "d-cat8.jpg",
        password: "123456",
        caption: "i am super cute",
        living_location: "Korea",
        status: "activated",
      },
      {
        username: "Nana",
        email: "Nana@gmail.com",
        profile_pic: "d-cat9.jpg",
        blog_image: "d-cat9.jpg",
        password: "123456",
        caption: "i am super cute",
        living_location: "Korea",
        status: "activated",
      },
      {
        username: "James",
        email: "James@gmail.com",
        profile_pic: "d-cat10.jpg",
        blog_image: "d-cat10.jpg",
        password: "123456",
        caption: "i am super cute",
        living_location: "Korea",
        status: "activated",
      },
      {
        username: "Adam",
        email: "Adam@gmail.com",
        profile_pic: "d-cat11.jpg",
        blog_image: "d-cat11.jpg",
        password: "123456",
        caption: "i am super cute",
        living_location: "Korea",
        status: "activated",
      },
      {
        username: "Alex",
        email: "Alex@gmail.com",
        profile_pic: "d-cat12.jpg",
        blog_image: "d-cat12.jpg",
        password: "123456",
        caption: "i am super cute",
        living_location: "Korea",
        status: "activated",
      },
      {
        username: "Gordan",
        email: "Gordan@gmail.com",
        profile_pic: "d-cat13.jpg",
        blog_image: "d-cat13.jpg",
        password: "123456",
        caption: "i am super cute",
        living_location: "Korea",
        status: "activated",
      },
      {
        username: "CM",
        email: "cm@gmail.com",
        profile_pic: "d-cat4.jpg",
        blog_image: "d-cat4.jpg",
        password: "123456",
        caption: "i am super cute",
        living_location: "Korea",
        status: "activated",
      },
      {
        username: "Machacel",
        email: "machacel@gmail.com",
        profile_pic: "d-cat5.jpg",
        blog_image: "d-cat5.jpg",
        password: "123456",
        caption: "i am super cute",
        living_location: "Korea",
        status: "activated",
      },
      {
        username: "Manson",
        email: "mansonl@gmail.com",
        profile_pic: "d-cat6.jpg",
        blog_image: "d-cat6.jpg",
        password: "123456",
        caption: "i am super cute",
        living_location: "Korea",
        status: "activated",
      },
      {
        username: "Paul",
        email: "Paul@gmail.com",
        profile_pic: "d-cat7.jpg",
        blog_image: "d-cat7.jpg",
        password: "123456",
        caption: "i am super cute",
        living_location: "Korea",
        status: "activated",
      },
    ]);

    await txn.commit();
    return;
  } catch (err) {
    console.log(err);
    await txn.rollback();
    return;
  }
}
